#                                                                        #
# Configuration for the FLOW3 Framework                                  #
#                                                                        #
# This file contains additions to the base configuration for the FLOW3   #
# Framework. Just add your own modifications as necessary.               #
#                                                                        #
# Please refer to the default configuration file or the FLOW3 manual for #
# possible configuration options.                                        #
#                                                                        #

FLOW3:
  error:
    ##
    # Use the more meaningful debug exception handler.
    exceptionHandler: className: 'F3\FLOW3\Error\DebugExceptionHandler'
  
    ##
    # All errors should result in exceptions.
    errorHandler: exceptionalErrors: [%E_USER_ERROR%, %E_RECOVERABLE_ERROR%, %E_WARNING%, %E_NOTICE%, %E_USER_WARNING%, %E_USER_NOTICE%, %E_STRICT%]
  
  resource:
    ##
    # Cache each resource file with check for modification time.
    cache: strategy: file
  
  monitor:
    fileMonitor:
      enable: y
  
  reflection:
    detectClassChanges: y
  
  log:
    systemLogger:
      backendOptions: { logFileURL: %FLOW3_PATH_DATA%Logs/%FLOW3_SAPITYPE%/FLOW3_Development.log, createParentDirectories: y, severityThreshold: %LOG_DEBUG% }
